[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
edgemarket = "AfvTruVTsrMfqSe5Tgss6hEgYNkk9ADAGKupSQr2DbD8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/mac/fulltime-keys/deployer.json"

[scripts]
